#page title
page_title                                : Fetch                                     # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.
github_link                               : https://github.com/tbwfdu/fetch/releases  # Enter link to GitHub repository. 
app_icon                                  : assets/fetch.png                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
dbl_icon                                  : assets/dbl.png                            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Fetch                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_os                                    : windows                                   # Enter supported OS platforms - windows or apple
app_description                           : Workspace ONE Application Management Tool
app_os_title                              : Windows

# Information About Yourself
your_name                                 : Pete Lindley                                
your_link                                 : https://github.com/tbwfdu                     
your_city                                 : Down Under, Australia                                
email_address                             : thisispete@gmail.com
github_username                           : tbwfdu

# Feature List
features                                  :

  - title                                 : Over 7500+ Applications
    description                           : Fetch has a database of over 7500 Windows applications and a combined total of over 65,000 versions & architectures.
    fontawesome_icon_name                 : database
    
  - title                                 : Over 5000+ Icons
    description                           : Fetch now also has a repository of 5000+ App icons that are automatically uploaded to the Workspace ONE App Catalog.
    fontawesome_icon_name                 : images

  - title                                 : Comprehensive Search
    description                           : Search for an Application by name and automatically create its corresponding Native App in Workspace ONE UEM.
    fontawesome_icon_name                 : search

  - title                                 : Identify Application Updates
    description                           : Query your existing Workspace ONE UEM App Catalog and identify available updates from the Fetch database.
    fontawesome_icon_name                 : upload

  - title                                 : Upload your existing App Inventory
    description                           : Upload an existing app inventory/report of your existing device management platform and identify which applications can automatically be uploaded to Workspace ONE UEM.
    fontawesome_icon_name                 : file-import
    
  - title                                 : Upload your Existing Apps
    description                           : Use Juice to scan an existing folder of your previously downloaded or internally packaged/developed applications and automatically upload them to Workspace ONE in bulk.
    fontawesome_icon_name                 : list

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_os                                 : windows                                     # Set to: macos or windows

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

windows_icon_color                        : "#0078D4"
apple_icon_color                          : "#666666"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
kramdown:
  toc_levels: 1..6