title: Fetch
description: Windows App Lifecycle Tool for Workspace ONE
theme: just-the-docs

url: https://just-the-docs.github.io
search_enabled: false
aux_links:
  Fetch Repository: https://github.com/tbwfdu/fetch

logo: "/assets/images/fetch-logo.png"
favicon_ico: "/assets/images/favicon.ico"

callouts:
  warning:
    title: Warning
    color: red
  new:
    title: New!
    color: green
  info:
    title: Info
    color: blue
  important:
    color: yellow
  note:
    color: grey-dk